name       : libfilezilla
version    : 0.34.2
release    : 37
source     :
    - https://download.filezilla-project.org/libfilezilla/libfilezilla-0.34.2.tar.bz2 : 20a28b77ec21b380ad0202db0166ed1c7c9c22d45048dd6806d5ec9fe27fed4a
license    : GPL-2.0-or-later
component  : programming
summary    : libfilezilla
description: |
    libfilezilla is a small and modern C++ library, offering some basic functionality to build high-performing, platform-independent programs
builddeps  :
    - pkgconfig(cppunit) # check
    - pkgconfig(gnutls)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
