name       : libfilezilla
version    : 0.14.0
release    : 21
source     :
    - https://download.filezilla-project.org/libfilezilla/libfilezilla-0.14.0.tar.bz2 : 7fe34e2ab6a13dc01afd2a548acf547c4c8bfa348cece55d4eee7aad50fa8e95
license    : GPL-2.0-or-later
component  : programming
summary    : libfilezilla
description: |
    libfilezilla is a small and modern C++ library, offering some basic functionality to build high-performing, platform-independent programs
builddeps  :
    - pkgconfig(cppunit) # check
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
