name       : libfilezilla
version    : 0.11.1
release    : 13
source     :
    - http://download.filezilla-project.org/libfilezilla/libfilezilla-0.11.1.tar.bz2 : ecbaa674c0ad0b63df842b8cde17935a497dd58c3749baa281c67cf5878e64f7
license    : GPL-2.0
component  : programming
summary    : libfilezilla
description: |
    libfilezilla is a small and modern C++ library, offering some basic functionality to build high-performing, platform-independent programs
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
