name       : libfilezilla
version    : 0.13.2
release    : 20
source     :
    - https://download.filezilla-project.org/libfilezilla/libfilezilla-0.13.2.tar.bz2 : 294420cf49997ee604010324dd62b1dc3dc473b693bd6b93248913c598c62c7d
license    : GPL-2.0-or-later
component  : programming
summary    : libfilezilla
description: |
    libfilezilla is a small and modern C++ library, offering some basic functionality to build high-performing, platform-independent programs
builddeps  :
    - pkgconfig(cppunit) # check
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
