name       : libfilezilla
version    : 0.11.2
release    : 15
source     :
    - https://download.filezilla-project.org/libfilezilla/libfilezilla-0.11.2.tar.bz2 : 96e59946fcf6f9444abfb4aea9f9275b9fa66f868bed00571bc32898bb178472
license    : GPL-2.0
component  : programming
summary    : libfilezilla
description: |
    libfilezilla is a small and modern C++ library, offering some basic functionality to build high-performing, platform-independent programs
builddeps  :
    - pkgconfig(cppunit) # check
setup      : |
    %configure --disable-static 
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
