name       : libfilezilla
version    : 0.3.0
release    : 1
source     :
    - http://tenet.dl.sourceforge.net/project/filezilla/libfilezilla/0.3.0/libfilezilla-0.3.0.tar.bz2 : 1ca09836fc166f21cedb71a45e5efc0771650a74d9f611d1fe320f36b53fa42d
license    : GPL-2.0
summary    : libfilezilla
description: |
    libfilezilla is a small and modern C++ library, offering some basic functionality to build high-performing, platform-independent programs
builddeps  :
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
