name       : libfilezilla
version    : 0.18.1
release    : 25
source     :
    - https://download.filezilla-project.org/libfilezilla/libfilezilla-0.18.1.tar.bz2 : cb7bae8a27a6ff7ea37c89a0ed4347d5c7b0c847473b29894dcadc154b8a7f97
license    : GPL-2.0-or-later
component  : programming
summary    : libfilezilla
description: |
    libfilezilla is a small and modern C++ library, offering some basic functionality to build high-performing, platform-independent programs
builddeps  :
    - pkgconfig(cppunit) # check
    - pkgconfig(gnutls)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
