name       : libfilezilla
version    : 0.7.1
release    : 6
source     :
    - http://internode.dl.sourceforge.net/project/filezilla/libfilezilla/0.7.1/libfilezilla-0.7.1.tar.bz2 : d95d2db75e523462c3f4b72b663b395dfe988cb71c3abef609f794a155a6ddd3
license    : GPL-2.0
component  : programming
summary    : libfilezilla
description: |
    libfilezilla is a small and modern C++ library, offering some basic functionality to build high-performing, platform-independent programs
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
