name       : libfilezilla
version    : 0.35.0
release    : 38
source     :
    - https://download.filezilla-project.org/libfilezilla/libfilezilla-0.35.0.tar.bz2 : eee2510dce3d0691ea73dc1da10fac7db1215b0ba9eefa616df305368b092ae8
license    : GPL-2.0-or-later
component  : programming
summary    : libfilezilla
description: |
    libfilezilla is a small and modern C++ library, offering some basic functionality to build high-performing, platform-independent programs
builddeps  :
    - pkgconfig(cppunit) # check
    - pkgconfig(gnutls)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
