name       : libfilezilla
version    : 0.22.0
release    : 32
source     :
    - https://download.filezilla-project.org/libfilezilla/libfilezilla-0.22.0.tar.bz2 : c5f660c4b339ed6a9e89ec0bafd5d39ba53cb3a3b52051bc571bb74e03ef8f7a
license    : GPL-2.0-or-later
component  : programming
summary    : libfilezilla
description: |
    libfilezilla is a small and modern C++ library, offering some basic functionality to build high-performing, platform-independent programs
builddeps  :
    - pkgconfig(cppunit) # check
    - pkgconfig(gnutls)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
