name       : libfilezilla
version    : 0.36.0
release    : 42
source     :
    - https://download.filezilla-project.org/libfilezilla/libfilezilla-0.36.0.tar.bz2 : c0271c18ede7fbbc826b21c972c2cb0ff96744ee5a15c91d8d74e9bc3853a872
license    : GPL-2.0-or-later
component  : programming
summary    : libfilezilla
description: |
    libfilezilla is a small and modern C++ library, offering some basic functionality to build high-performing, platform-independent programs
builddeps  :
    - pkgconfig(cppunit) # check
    - pkgconfig(gnutls)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
