name       : libfilezilla
version    : 0.12.2
release    : 17
source     :
    - https://download.filezilla-project.org/libfilezilla/libfilezilla-0.12.2.tar.bz2 : 778c166fde3a87e04a0524a4bf92c3eea1f0836c20119dd0859c9cd9380c86ec
license    : GPL-2.0-or-later
component  : programming
summary    : libfilezilla
description: |
    libfilezilla is a small and modern C++ library, offering some basic functionality to build high-performing, platform-independent programs
builddeps  :
    - pkgconfig(cppunit) # check
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
