name       : libfilezilla
version    : 0.20.1
release    : 29
source     :
    - https://download.filezilla-project.org/libfilezilla/libfilezilla-0.20.1.tar.bz2 : 07a777daa27a49ea9b63b1636f713196193ff65fcc63a8ab5947ee707e2be884
license    : GPL-2.0-or-later
component  : programming
summary    : libfilezilla
description: |
    libfilezilla is a small and modern C++ library, offering some basic functionality to build high-performing, platform-independent programs
builddeps  :
    - pkgconfig(cppunit) # check
    - pkgconfig(gnutls)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
