name       : libfilezilla
version    : 0.9.2
release    : 9
source     :
    - http://download.filezilla-project.org/libfilezilla/libfilezilla-0.9.2.tar.bz2 : c162e8a23555b3bbc707cf240b0b4122ea2975d6d8b10744325b968f656b3be3
license    : GPL-2.0
component  : programming
summary    : libfilezilla
description: |
    libfilezilla is a small and modern C++ library, offering some basic functionality to build high-performing, platform-independent programs
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
