name       : libfilezilla
version    : 0.28.0
release    : 36
source     :
    - https://download.filezilla-project.org/libfilezilla/libfilezilla-0.28.0.tar.bz2 : e7c021070e6101838728b19691d0c480924f4640e5b04adf41e35206e7041638
license    : GPL-2.0-or-later
component  : programming
summary    : libfilezilla
description: |
    libfilezilla is a small and modern C++ library, offering some basic functionality to build high-performing, platform-independent programs
builddeps  :
    - pkgconfig(cppunit) # check
    - pkgconfig(gnutls)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
