name       : libfilezilla
version    : 0.18.2
release    : 26
source     :
    - https://download.filezilla-project.org/libfilezilla/libfilezilla-0.18.2.tar.bz2 : 40d86929b486a6809c4b52d607f21a00e634e0b9b792504fe2964c117b522dc9
license    : GPL-2.0-or-later
component  : programming
summary    : libfilezilla
description: |
    libfilezilla is a small and modern C++ library, offering some basic functionality to build high-performing, platform-independent programs
builddeps  :
    - pkgconfig(cppunit) # check
    - pkgconfig(gnutls)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
