name       : libfilezilla
version    : 0.19.3
release    : 28
source     :
    - https://download.filezilla-project.org/libfilezilla/libfilezilla-0.19.3.tar.bz2 : a43d49f86d5550e9a81aee2394bac066333d5bb47943e92c629cb9d52037b43a
license    : GPL-2.0-or-later
component  : programming
summary    : libfilezilla
description: |
    libfilezilla is a small and modern C++ library, offering some basic functionality to build high-performing, platform-independent programs
builddeps  :
    - pkgconfig(cppunit) # check
    - pkgconfig(gnutls)
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
check      : |
    %make check
