name       : libfilezilla
version    : 0.10.0
release    : 14
source     :
    - http://download.filezilla-project.org/libfilezilla/libfilezilla-0.10.0.tar.bz2 : bd10176c44f421a20c92c66d85a7a277dcc0d1c4b57cf20b7b6ba24cb4493382
license    : GPL-2.0
component  : programming
summary    : libfilezilla
description: |
    libfilezilla is a small and modern C++ library, offering some basic functionality to build high-performing, platform-independent programs
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
