name       : libfilezilla
version    : 0.11.0
release    : 11
source     :
    - http://download.filezilla-project.org/libfilezilla/libfilezilla-0.11.0.tar.bz2 : cc7467241c8905de98773b414ce445d6f9ff3bf3105f2d16cecab76404879ed0
license    : GPL-2.0
component  : programming
summary    : libfilezilla
description: |
    libfilezilla is a small and modern C++ library, offering some basic functionality to build high-performing, platform-independent programs
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
