name       : libfilezilla
version    : 0.5.1
release    : 2
source     :
    - http://tenet.dl.sourceforge.net/project/filezilla/libfilezilla/0.5.1/libfilezilla-0.5.1.tar.bz2 : 585b58eecc43f3803a3f1b1ee69dce7b57bae5a49d85514044a7c95da299b7f9
license    : GPL-2.0
component  : programming
summary    : libfilezilla
description: |
    libfilezilla is a small and modern C++ library, offering some basic functionality to build high-performing, platform-independent programs
setup      : |
    %configure --disable-static
build      : |
    %make
install    : |
    %make_install
